// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous 
// two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed 
// four million, find the sum of the even-valued terms.

#include <iostream>

int method() {
    int sum = 0;
    int prev = 1;
    int curr = 2;
    for (int next = 3; next < 4000000; next = curr+prev) {
        if (next%2 == 0) {
            sum += next;
        }
        prev = curr;
        curr = next;
    }
    return sum+2;
}

int main() {
    std::cout << method() << std::endl;
}

//Answer: 4613732